name: Release and deploy Go_Fortune
#trigger
on:
  push:
    branches:
      - "v[0-9]+.[0-9]+"

# Jobs in the workflow
jobs:
#job name
  mrelease-and-deploy:
    #OS that this workflow will be running on 1
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    #list of steps to perform task
    steps: 
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the  current repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Release the current version
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GH_TOKEN_GF }}


    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Send Slack Notification
      id: slak
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission"                
                }              
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text":"*Name:*\nKaung Myat Lwin"
                  },
                  {
                    "type": "mrkdwn",
                    "text":"*Metriculation:\nA0265075B"
                  }                
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text":"*Email:*\n<mailto:e1045750@u.nus.edu|e1045750@u.nus.edu>"
                  },
                  {
                    "type": "mrkdwn",
                    "text":"*Repository:*\n<https://github.com/Lycanx4/GoFortune>"
                  }                
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text":"*Deployment:*\n<https://svc-gofortune-production.up.railway.app>"
                  }               
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text":"<https://svc-gofortune-production.up.railway.app | Open Application>"
                  }               
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK